api_files_show_all:
    path: /api/files
    controller: App\Controller\FileController::showAll
    methods: [GET]

api_files_show_one:
    path: /api/files/{token}
    controller: App\Controller\FileController::showOne
    methods: [GET]

api_files_download:
    path: /api/files/{token}/download
    controller: App\Controller\FileController::download
    methods: [GET]

api_files_upload:
    path: /api/files
    controller: App\Controller\FileController::upload
    methods: [POST]